### ISSUE TITLE
node-pre-gyp WARN Hit error EACCES: permission denied

### ISSUE THREAD

**Issue by xgrons** [n0x073/CR-dl#3]
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-libcurl/lib/binding'
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-lib

**Comment by n0x073** [comment]
Which os do you use?

**Comment by Tizioincognit0** [comment]
I had the same issue on macOS 10.14.6 Mojave but I fixed it with this command: `sudo npm install -g @n0x073/cr-dl --unsafe-perm=true`.

**Comment by xgrons** [comment]
> Which os do you use?

Ubuntu

**Comment by xgrons** [comment]
> I had the same issue on macOS 10.14.6 Mojave but I fixed it with this command: `sudo npm install -g @n0x073/cr-dl --unsafe-perm=true`.

Thanks i will try

**Comment by n0x073** [comment]
The unsafe-perm arg worked?
Would you prefer a docker image?

**Comment by xgrons** [comment]
Thanks it worked when i updated node
